import Navbar from "./components/navigation/navbar/Navbar";
import { CartProvider } from "./context/CartContext";
import Provider from "./context/ClientProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import { authOptions } from "@/utils/authOptions";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Parasol Labs",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions)
  return (
    <html lang="en" className="backgroundMain">
      <head>
        <link rel="icon" type="image/x-icon" href="/images/favicon.ico"></link>
      </head>
      <body className={inter.className}>
        <Provider session={session}>
          <CartProvider>
            <Navbar />
            {children}
          </CartProvider>
        </Provider>
      </body>
    </html>
  );
}
